module.exports = {
	filleules : {
					horodateur: "horodateur",
					nom : "nom",
					prenom:"prénom",
					email: "email",
					societe:"société/Ecole",
					experience:"annéesD\'expérienceDansLeDomaineInformatique/AnnéesD\'étudesPourLesÉtudiants",
					profession:"profession/SpécialitéDansL\'école",
					specialite:"spécialités/domaineTechnique(web,Mobile,Data,Infra,Ops,…?)",
					ville:"région/ville",
					telephone:"noTéléphone",
					twitter:"urlTwitter",
					linkedin:"urlLinkedin",
					facebook: "urlFacebook",
					mailingList:"etesVousAbonnéeÀLaMailingListDuchess?",
					description:"quelquesMotsPourVousPrésenterAuxMarraines,QueRecherchezVous?",
					modeInteraction:"avezVousUnModeD\'interactionPréféré?",
					map:"acceptezVousDeFigurerSurLaMapDesDuchessFranceSurLeSiteDeMarrainage?",
					codePostal:"quelEstVotreCodePostal?"
				},

	marraines : {
					horodateur: "horodateur",
					nom : "nom",
					prenom:"prénom",
					email: "email",
					societe:"société",
					experience:"annéesD\'expérienceDansLeDomaineInformatique",
					profession:"profession",
					specialite:"spécialités/domaineTechnique(web,Mobile,Data,Infra,Ops,…?)",
					ville:"région/ville",
					telephone:"noTéléphone",
					twitter:"urlTwitter",
					linkedin:"urlLinkedinOuViadéo",
					facebook: "urlFacebook",
					mailingList:"etesVousAbonnéeÀLaMailingListDuchess?",
					description:"quelquesMotsPourVousPrésenterAuxFilleules",
					modeInteraction:"avezVousUnModeD\'interactionPréféréPourÉchangerAvecVotreFilleule?",
					map:"acceptezVousD\'êtreVisibleSurLaCarteDeLocalisationDesDuchesses?",
					codePostal:"quelEstVotreCodePostal?"
				},
};